openapi: 3.2.0
info:
  contact:
    name: Instock
    email: info@instock.com
    url: https://instock.com
  license:
    name: Instock
    url: https://instock.com
  title: Instock API reference Moves API
  version: 0.1.0
  description: '# Overview

    This reference is a comprehensive guide to understanding of Instock API and is aimed to

    help developers to integrate their Host system with Instock Cloud (Incloud).'
servers:
- url: https://api.instock.com/v1
security:
- bearerAuth: []
tags:
- name: Moves
  description: 'Moves allow to retrieve data on article(s) flow in and out of of a particular site owned by your organization.

    List moves of all articles or retrieve them for a single article.


    **Note**: Refine your search with `from_timestamp` and `to_timestamp` — most recent moves will be on top of the list.'
paths:
  /{site_id}/moves:
    get:
      tags:
      - Moves
      summary: List all articles moves
      description: 'Returns a paginated list of all moves for all articles within specific site.


        **Note**: Results are sorted in a descending order of their timestamps, meaning the latest results are displayed first.'
      operationId: getAllArticlesMoves
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: 'curl -X GET ''https://api.instock.com/v1/{SITE_ID}/moves?start_cursor={START_CURSOR}&page_size={PAGE_SIZE}&from_timestamp={FROM_TIMESTAMP}&to_timestamp={TO_TIMESTAMP}&to_cell_id={CELL_ID}'' \

          -H ''Authorization: Bearer {ACCESS_TOKEN}''

          '
      parameters:
      - $ref: '#/components/parameters/instockCorrelationID'
      - $ref: '#/components/parameters/siteID'
      - $ref: '#/components/parameters/startCursor'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/fromTimestamp'
      - $ref: '#/components/parameters/toTimestamp'
      - $ref: '#/components/parameters/toCellID'
      responses:
        '200':
          description: Successful operation.
          headers:
            Instock-Response-ID:
              $ref: '#/components/headers/instockRequestID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movesAllArticles'
              examples:
                Articles moves:
                  $ref: '#/components/examples/allArticleMoves'
        '400':
          description: Bad request
          headers:
            Instock-Response-ID:
              $ref: '#/components/headers/instockRequestID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Bad request:
                  value:
                    code: bad_request
                    message: Request body/path/query params cannot be validated.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Not found
          headers:
            Instock-Response-ID:
              $ref: '#/components/headers/instockRequestID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Site doesn't exist:
                  value:
                    code: resource_not_found
                    message: site_id doesn't exist.
        '500':
          $ref: '#/components/responses/InternalServerError'
  /{site_id}/moves/{article_id}:
    get:
      tags:
      - Moves
      summary: Retrieve article moves
      description: 'Returns a paginated list of all moves of a single article within a specific site.


        **Note**: Results are sorted in a descending order of their timestamps, meaning the latest results are displayed first.'
      operationId: getArticleIdMove
      x-codeSamples:
      - lang: cURL
        label: cURL
        source: 'curl -X GET ''https://api.instock.com/v1/{SITE_ID}/moves/{ARTICLE_ID}?start_cursor={START_CURSOR}&page_size={PAGE_SIZE}&from_timestamp={FROM_TIMESTAMP}&to_timestamp={TO_TIMESTAMP}'' \

          -H ''Authorization: Bearer {ACCESS_TOKEN}''

          '
      parameters:
      - $ref: '#/components/parameters/instockCorrelationID'
      - $ref: '#/components/parameters/siteID'
      - $ref: '#/components/parameters/articleID'
      - $ref: '#/components/parameters/startCursor'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/fromTimestamp'
      - $ref: '#/components/parameters/toTimestamp'
      responses:
        '200':
          description: Successful operation
          headers:
            Instock-Response-ID:
              $ref: '#/components/headers/instockRequestID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/movesArticleId'
              examples:
                Moves of a single article:
                  $ref: '#/components/examples/singleArticleMoves'
        '400':
          description: Bad request
          headers:
            Instock-Response-ID:
              $ref: '#/components/headers/instockRequestID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Bad request:
                  value:
                    code: bad_request
                    message: Request body/path/query params cannot be validated.
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Not found
          headers:
            Instock-Response-ID:
              $ref: '#/components/headers/instockRequestID'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Site doesn't exist:
                  value:
                    code: resource_not_found
                    message: site_id doesn't exist.
                Article doesn't exist:
                  value:
                    code: resource_not_found
                    message: article_id doesn't exist.
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  parameters:
    startCursor:
      name: start_cursor
      in: query
      required: false
      description: "Cursor returned from a previous response, \nused to request the next page of the results. \n"
      schema:
        type: string
        example: fe2cc560-036c-44cd-90e8-294d5a74cebc
        default: ''
    fromTimestamp:
      name: from_timestamp
      in: query
      required: true
      schema:
        $ref: '#/components/schemas/movesFromTimestamp'
    instockCorrelationID:
      name: Instock-Correlation-ID
      description: Optional header ID to track and analyze requests and behaviors across your Host system.
      in: header
      required: false
      schema:
        type: string
    articleID:
      name: article_id
      in: path
      description: ID of an article. Unique in scope of your organization(s).
      required: true
      schema:
        $ref: '#/components/schemas/articleId'
      example: 016000487727
    toTimestamp:
      name: to_timestamp
      in: query
      required: true
      schema:
        $ref: '#/components/schemas/movesToTimestamp'
    siteID:
      name: site_id
      in: path
      required: true
      description: ID of Instock site. Globally unique.
      schema:
        $ref: '#/components/schemas/siteId'
      example: 1.1.0-1
    pageSize:
      name: page_size
      in: query
      required: false
      description: "The number of articles returned in response. \nDefault (minimum) value is 10, maximum value is 1000.\n"
      schema:
        type: integer
        format: int64
        example: 10
        default: 10
        maximum: 1000
    toCellID:
      name: to_cell_id
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/toCellId'
  schemas:
    movesArticleId:
      type: object
      properties:
        has_more:
          type: boolean
          description: 'If `true`, `next_cursor` to access next part of the list.

            If `false`, response includes the end of the list.

            '
        next_cursor:
          type: string
          description: "Only available when `has_more` is `true`.\nUsed to retrieve the next page of results by \npassing the value as the `start_cursor` parameter \nto the same endpoint.\n"
        org_id:
          type: string
          description: ID of an organization. Globally unique.
        site_id:
          type: string
          description: ID of Instock site. Globally unique.
        article_id:
          $ref: '#/components/schemas/articleId'
        moves:
          description: Move records of article(s).
          type: array
          items:
            type: object
            properties:
              article_id:
                $ref: '#/components/schemas/articleId'
              qty:
                type: integer
                format: int64
                description: Quantity of items of a specific article moved between cells.
              move_timestamp:
                type: string
                format: date-time
                description: Move timestamp of specific article.
              user_id:
                type: string
                description: Unique ID of a user that performed the move.
              order_id:
                $ref: '#/components/schemas/orderId'
              from_cell_id:
                type: string
                description: Cell from which specific article moved.
              to_cell_id:
                $ref: '#/components/schemas/toCellId'
              from_account_id:
                type: string
                description: Account that passed a specific article.
              to_account_id:
                type: string
                description: Account that registered a specific article.
    toCellId:
      type: string
      description: ID of the target storage cell to which a specific article moved.
      minLength: 1
      maxLength: 1024
      example: VM-TIY6J-P001
    siteId:
      type: string
      description: ID of Instock site. Globally unique.
    movesAllArticles:
      type: object
      properties:
        has_more:
          type: boolean
          description: 'If `true`, `next_cursor` to access next part of the list.

            If `false`, response includes the end of the list.

            '
        next_cursor:
          type: string
          description: "Only available when `has_more` is `true`.\nUsed to retrieve the next page of results by \npassing the value as the `start_cursor` parameter \nto the same endpoint.\n"
        org_id:
          type: string
          description: ID of an organization. Globally unique.
        site_id:
          type: string
          description: ID of Instock site. Globally unique.
        moves:
          description: Move records of article(s).
          type: array
          items:
            type: object
            properties:
              article_id:
                $ref: '#/components/schemas/articleId'
              qty:
                type: integer
                format: int64
                description: Quantity of items of a specific article moved between cells.
              move_timestamp:
                type: string
                format: date-time
                description: Move timestamp of specific article.
              user_id:
                type: string
                description: Unique ID of a user that performed the move.
              order_id:
                $ref: '#/components/schemas/orderId'
              from_cell_id:
                type: string
                description: Cell from which specific article moved.
              to_cell_id:
                $ref: '#/components/schemas/toCellId'
              from_account_id:
                type: string
                description: Account that passed a specific article.
              to_account_id:
                type: string
                description: Account that registered a specific article.
    orderId:
      type: string
      description: ID of an order. Unique in scope of your organization(s).
      pattern: ^[a-zA-Z0-9_+.:-]+$
      minLength: 1
      maxLength: 128
    movesToTimestamp:
      type: string
      format: date-time
      description: Finish date of article moves [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339).
      example: '2023-01-01T00:00:00Z'
    articleId:
      type: string
      description: ID of an article. Unique in scope of your organization(s).
      pattern: ^[a-zA-Z0-9_+.]+$
    Error:
      type: object
      properties:
        code:
          description: Code that identifies the reason of an error.
          type: string
        message:
          description: Description of an error.
          type: string
    movesFromTimestamp:
      type: string
      format: date-time
      description: Start date of article moves [RFC 3339](https://www.rfc-editor.org/rfc/rfc3339).
      example: '2023-01-01T00:00:00Z'
  responses:
    Forbidden:
      description: Forbidden
      headers:
        Instock-Response-ID:
          $ref: '#/components/headers/instockRequestID'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: forbidden
            message: API key doesn't have permissions to perform the request.
    InternalServerError:
      description: Internal server error
      headers:
        Instock-Response-ID:
          $ref: '#/components/headers/instockRequestID'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: internal_server_error
            message: Unexpected error occurred.
    Unauthorized:
      description: Unauthorized
      headers:
        Instock-Response-ID:
          $ref: '#/components/headers/instockRequestID'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: unauthorized
            message: API key is not valid.
  examples:
    singleArticleMoves:
      value:
        has_more: false
        next_cursor: ''
        org_id: org_id_001
        site_id: 1.1.0-1
        article_id: '1003000031678'
        moves:
        - article_id: '1003000031678'
          qty: 12
          move_timestamp: '2022-06-06T14:38:39Z'
          user_id: '00001'
          order_id: '00132431'
          from_cell_id: cell_001
          to_cell_id: cell_002
          from_account_id: account_001
          to_account_id: account_002
        - article_id: '1003000031678'
          qty: 2
          move_timestamp: '2022-06-03T14:38:39Z'
          user_id: '00001'
          order_id: '00132457'
          from_cell_id: cell_003
          to_cell_id: cell_004
          from_account_id: account_001
          to_account_id: account_002
    allArticleMoves:
      value:
        has_more: false
        next_cursor: ''
        org_id: org_id_001
        site_id: 1.1.0-1
        moves:
        - article_id: '116000487727'
          qty: 4
          move_timestamp: '2022-06-06T14:38:39Z'
          user_id: '00001'
          order_id: '00132457'
          from_cell_id: cell_005
          to_cell_id: cell_004
          from_account_id: account_001
          to_account_id: account_002
        - article_id: '1003000031678'
          qty: 12
          move_timestamp: '2022-06-06T14:38:39Z'
          user_id: '00002'
          order_id: '00132431'
          from_cell_id: cell_001
          to_cell_id: cell_002
          from_account_id: account_001
          to_account_id: account_002
        - article_id: '1003000031678'
          qty: 2
          move_timestamp: '2022-06-03T14:38:39Z'
          user_id: '00003'
          order_id: '00132623'
          from_cell_id: cell_003
          to_cell_id: cell_004
          from_account_id: account_001
          to_account_id: account_002
  headers:
    instockRequestID:
      description: Auto-generated ID in the response headers to reference a specific request, useful for debugging or seeking support.
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      type: http
      scheme: bearer
